version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: cisdi_csv_cleaner_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: csv_cleaner
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

volumes:
  postgres_data_new:
