version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: cisdi_csv_cleaner_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: csv_cleaner
      POSTGRES_HOST_AUTH_METHOD: trust
    # 高配开发机 PostgreSQL 参数
    command: >
      postgres
      -c shared_buffers=256MB
      -c work_mem=16MB
      -c maintenance_work_mem=128MB
      -c effective_cache_size=512MB
      -c max_connections=100
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

volumes:
  postgres_data_new:
